// <auto-generated />
using System;
using Ilumno.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ilumno.Data.EF.Migrations
{
    [DbContext(typeof(BackEndDbContext))]
    [Migration("20240824001205_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ilumno.Core.Formularios.Models.Formulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Formulario");
                });

            modelBuilder.Entity("Ilumno.Core.Paises.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Paises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Perú"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Panamá"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Chile"
                        });
                });

            modelBuilder.Entity("Ilumno.Core.TiposDocumentos.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDocumentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cédula de Extrangería"
                        });
                });

            modelBuilder.Entity("Ilumno.Core.Formularios.Models.Formulario", b =>
                {
                    b.HasOne("Ilumno.Core.Paises.Models.Pais", "Pais")
                        .WithMany("Formularios")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ilumno.Core.TiposDocumentos.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Formularios")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Ilumno.Core.Paises.Models.Pais", b =>
                {
                    b.Navigation("Formularios");
                });

            modelBuilder.Entity("Ilumno.Core.TiposDocumentos.Models.TipoDocumento", b =>
                {
                    b.Navigation("Formularios");
                });
#pragma warning restore 612, 618
        }
    }
}
